### ISSUE TITLE
Incorrect parsing of comments after preprocessor directives

### ISSUE THREAD

**Issue by amachronic** [tree-sitter/tree-sitter-c#59]
```c
#define FOO 1 /* this comment is not parsed as a comment */
#define BAR   /* although this comment is */
```
I found this while trying [emacs-tree-sitter](https://github.com/ubolonton/emacs-tree-sitter). Its debug output:
```
translation_unit:
  preproc_def:
    identifier:
    preproc_arg:
  preproc_def:
    identifier:
    comment:
```

The root of the problem seems to be `preproc_arg`:
```js
preproc_arg: $ => token(prec(-1, repeat1(/.|\\\r?\n/)))
```

The C preprocessor interprets both `//` and `/* */` style comments and replaces them with a single whitespace according to C99. It seems like `token` might the root cause of the issue by preventing tree-sitter from applying `extras` (which normally handles comments).

This would also be the cause of #55 and #44, also [this](https://github.com/tree-sitter/tree-sitter-cpp/issues/63) issue in tree-sitter-cpp.
