### ISSUE TITLE
tree-sitter-c doesn't expand preproc_arg

### ISSUE THREAD

**Issue by coiby** [tree-sitter/tree-sitter-c#87]
```c
#define TX_DESC_PER_IOCB 8

#define TX_DESC_PER_OAL ((MAX_SKB_FRAGS - TX_DESC_PER_IOCB) + 2)
```
is parsed as follows,
```yaml
translation_unit [0, 0] - [3, 0]
  preproc_def [0, 0] - [2, 0]
    name: identifier [0, 8] - [0, 24]
    value: preproc_arg [0, 24] - [0, 26]
  preproc_def [2, 0] - [3, 0]
    name: identifier [2, 8] - [2, 23]
    value: preproc_arg [2, 23] - [2, 64]
```

I expect tree-sitter-c can further parse `((MAX_SKB_FRAGS - TX_DESC_PER_IOCB) + 2)` into sub-elements.
